"""Initial Migration

Revision ID: e68beadd1368
Revises: 
Create Date: 2026-05-28 18:58:05.834871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68beadd1368'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_stock'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('portfolios',
    sa.Column('id_port', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_port')
    )
    op.create_table('predictions',
    sa.Column('id_prev', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('version_model', sa.String(length=100), nullable=False),
    sa.Column('prob_lstm', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('prob_xgb', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('prob_ensemble', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('final_forecast', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_prev')
    )
    op.create_index('idx_stock_forecast_date', 'predictions', ['id_stock', 'forecast_date'], unique=False)
    op.create_table('price_history',
    sa.Column('id_hist', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_hist')
    )
    op.create_index('idx_stock_recorded_at', 'price_history', ['id_stock', 'recorded_at'], unique=False)
    op.create_table('realtime_prices',
    sa.Column('id_temp', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('percent_change', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_temp'),
    sa.UniqueConstraint('id_stock')
    )
    op.create_table('alerts',
    sa.Column('id_alert', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_port', sa.Integer(), nullable=False),
    sa.Column('id_prev', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_port'], ['portfolios.id_port'], ),
    sa.ForeignKeyConstraint(['id_prev'], ['predictions.id_prev'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_alert')
    )
    op.create_table('portfolio_stocks',
    sa.Column('id_port_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_port', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id_port'], ['portfolios.id_port'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id_stock'], ),
    sa.PrimaryKeyConstraint('id_port_stock'),
    sa.UniqueConstraint('id_stock', 'id_port', name='uq_stock_port')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_stocks')
    op.drop_table('alerts')
    op.drop_table('realtime_prices')
    op.drop_index('idx_stock_recorded_at', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_stock_forecast_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('portfolios')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
